name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Hello world action
    runs-on: k3d-runner-deployment
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Simon"
